### ISSUE TITLE
"Empty Array" display issues in tree mode

### ISSUE THREAD

**Issue by KateWilkins** [josdejong/jsoneditor#308]
If an array is defined in the json below the top level and its empty then its displayed as "(empty array)" however it breaks the indentation for the whole tree display.

![screen shot 2016-06-14 at 10 29 01](https://cloud.githubusercontent.com/assets/11190627/16037985/de40eb98-321a-11e6-8801-b255cb5953e1.png)

It seems that the empty <td></td> for the preceeding columns to the left is not being generated.

**Comment by josdejong** [comment]
Thanks for reporting. How can I reproduce this? When I try with the [online version](http://jsoneditoronline.org) things work just fine. Can it be that there are CSS conflicts with other parts of your application or something like that?

**Comment by KateWilkins** [comment]
Jose, thanks for responding, yes, looks like you are right, is a css issue, not sure what yet.

**Comment by josdejong** [comment]
ok thanks for the feedback

**Comment by KateWilkins** [comment]
Jos,
Having done some more digging yesterday I've worked out the issue and managed to isolate it down to options rather than css, it seems if I force things into ReadOnly mode then the problem appears, when in edit mode then it displays just fine.

Bad Display
            var options = {"mode": "tree", "search":true, "onEditable":function(node){return false;} };
            var editor = new JSONEditor(container, options);

Good Display
            var options = {"mode": "tree", "search":true};
            var editor = new JSONEditor(container, options);

**Comment by josdejong** [comment]
Ah, thanks! now I can reproduce the issue:

http://jsbin.com/deseqit/edit?html,output

**Comment by josdejong** [comment]
I fixed this bug, will be corrected in the first next release.

**Comment by HiroAgustin** [comment]
Hi, I'm having the same problem, thanks for the fix! Looking forward to the release.
Just wanted to add that this is happens only when the field attribute is not editable.
If you change the jsbin to return `{ field: false, value: true }` you'll see the problem remains.

Again, thank you for the fix!

**Comment by josdejong** [comment]
O no! I forgot to do the release, sorry!!! I will release v5.5.7 today.

**Comment by HiroAgustin** [comment]
Awesome! Thanks

**Comment by josdejong** [comment]
Ok v5.5.7 is now available. Sorry for the inconvenience.

**Comment by HiroAgustin** [comment]
🎉 🎊  No inconvenience, thank you for the quick response. The editor is great!

**Comment by josdejong** [comment]
Thanks, you're welcome :)

**Comment by KateWilkins** [comment]
Thanks for the release.
