### ISSUE TITLE
Ask whether users want to load back last session or not

### ISSUE THREAD

**Issue by pacproduct** [josdejong/jsoneditor#371]
Hello :)

At the moment, this great tool automatically loads last session's data when accessing http://jsoneditoronline.org/

That is useful most of the time, however when last session was painfully heavy to parse (e.g. too much data) accessing the site is quite long because it loads the painful data again, even if we probably don't want it back.

My suggestion would be to ask the user whether last session should be loaded or not (for instance http://geojson.io/ does that), or to provide a button in the top bar offering a way to load latest session if the user wishes to restore it.

That'd be a cool user experience improvement I think :)

_Great tool otherwise, it really is useful :+1:_

**Comment by josdejong** [comment]
That's a smart idea. I've had this issue myself too in the past.

For "regular" use though its convenient _not_ to have to answer a question every time you load the web application, that's annoying too.

Maybe it's an idea to only ask to load session of last time when the file is large, for example when larger than 100 kB or something.

**Comment by pacproduct** [comment]
I must say I like @josdejong's idea, even though it's probably quite difficult to know where to draw the line, as "a large file" means quite different things depending on users' computers.  

This said, as most users probably use this tool for quite small files and tests (presumably), we could probably set this threshold to a low-ish value. I gave it a try with 129KB and it took around a second to load  (but I have a quite powerfull PC tailored for gaming... so I wouldn't take this figure as a good basis).  

Personally I would probably set this to something as low as 10KB.

**Comment by pacproduct** [comment]
I'm thinking: Ideally we should ask the user whether they want to reload last session only if parsing it took more than X ms (more than 1 or 2 seconds for instance, that would be okay I think).  
That implies timing how long it takes to parse entered text to be parsed, and save it in session. Why not? :) At least we wouldn't rely on an arbitrary file size.


Maybe I'm over-engineering the thing? ;)

**Comment by josdejong** [comment]
Yes, that's a great idea! Measuring time is what you're interested in in the end because loading should not take "too long". It's technically not that difficult either way.

**Comment by pacproduct** [comment]
As a side note: Looks like what actually takes most of the time is syntax coloring, not converting the left hand side string to JSon.

**Comment by josdejong** [comment]
Yes, we should measure how long rendering takes, how long the browser "hangs".

**Comment by josdejong** [comment]
I've implemented a simple message to ask if you want to load last data again when it took >3 seconds. Would be great if you can give it a try.

**Comment by pacproduct** [comment]
That's a great improvement, well done :)  
A few remarks on this new version:
See attached file for sample dummy files: [jsoneditor-tests.zip](https://github.com/josdejong/jsoneditor/files/925488/jsoneditor-tests.zip)

- I tried pasting the content of file "RandomJsonFile-5000-mini.json" to your editor: It took roughly 20s for it to appear. I closed the tab (note that I did not click the ">" button), and reopened the site in a new one: It did not ask me if I wanted to reload the data, even though it took long loading it.  
I tried the same scenario again, but this time with my computer in "energy saving mode" (cpu capped at 800Mhz): Took approx. 55s to paste the content of the file. Closing the tab and reopening it still did not ask me anything. What I noticed though is that while waiting the whole time, Google Chrome was displaying "Waiting for the cache to display" (well, my environment being French, the actual string was "En attente de l'affichage du cache"). I don't know what it means precisely, technically speaking...  
Finally, I decided to simply refresh this tab, and finally got your box asking me "`Loading data took very long last time, about 5 seconds. Do you want to load this data again?`". Only 5 seconds? Hm, how did that happen? I recall waiting way more than that... :) So I guess that there is a discrepancy somewhere between how long we actually have to wait, and what your software is able to time.    
All in all, I'm not sure if my tests are valid, but hopefully this could give you hints on how the site behaves for some of your users...
- Another thing: I tried a few more things with bigger files, and when the site really struggles with my files, the asking box usually appears the next time I open the site, which is good. When they are too big, apprently your site does not try to save them for the next time: closing and reopening it brings the previous set of data that wasn't too big (<5MB) apprently. That's a good thing too I guess.
- As a side note, when emptying completely the content of the left hand side editor and closing the site, loading the site back again triggers an error: `SyntaxError: Unexpected end of JSON input` because the loaded json is invalid. That is not necessarily very user friendly.

Hope all this helps.  
But honestly, situations described above are mostly edge-cases. Feels like it's mostly one-liner files (e.g. minified json files) that cause weird behaviors.

**Comment by josdejong** [comment]
Thanks for your feedback, very helpful.

Pasting text is indeed a very common one but not yet taken into account, it currently only checks when loading a file via "load from local disk" or via drag and drop. I will see whether I can hook into Ace editor when pasting text there. 

Not displaying the SyntaxError in case of an empty file makes sense.

**Comment by josdejong** [comment]
It's correct that minified JSON is heavy to load: that's the case for Ace editor (left panel) and in most IDE's I know of. The right panel (tree editor) mostly struggles when it has to render a lot in expanded state initially, like an array with a huge amount of items.

**Comment by pacproduct** [comment]
Aah ok. Well with the minified 5000 entry test file I provided above, it still doesn't ask me whether I want to load it again or not, when using the "load from disk" option, even though it takes almost 10 seconds to parse.  
I tried again in "power saving" mode: Took around 50s for the browser to become responsive again, then closed and reopened the site: This time I did get the pop up asking whether to load data again, but it was claiming my previous set of data took around 5s to load, which is still far from the truth :)  

I guess it's not that easy to time how long operations from other libraries take.  
Are you experiencing similar behaviors to what I see on my side?

**Comment by pacproduct** [comment]
Maybe another approach would be easier to implement and almost as nice from a user experience point of view:  
When opening up the site, it could simply load your default "empty" template every time, but offer a way to load back the previous set of data when there is one, like so for instance:  
![loadpreviousdata](https://cloud.githubusercontent.com/assets/2098407/25153843/61749a30-248e-11e7-96d8-59cddefbfa28.png)  

I see 2 advantages with this approach:
- First, loading the site will never take long again, as it will always default to a very light template.
- Second: If I click on the "Load last set of data" link without remembering what it was, it may take very long... but it wouldn't really be a big deal as I could simply close the site and reopen it in a new tab for _cancelling_ the long loading of the previous set.

What do you say? :)

**Comment by josdejong** [comment]
Hm I tried to download your test files from jsoneditor-tests.zip but it looks like the file is corrupted (downloads only 56 kB), could you try to upload again or mail it? Testing with the same files as you do would be helpful.

Interesting idea to turn the default behavior around: start empty and have a way to open last document instead of the other way around. We have to keep in mind though that with large documents we're talking about _exceptions_, typical documents are small and load in an instant, that shouldn't be a reason not to load the last document by default.
Most important to me is what the _typical_ behavior of a user is: when opening the website, does a user want to start empty or continue where they left most of the time? I still think the last one is the best: continue where you left. I think it's important in general to always just continue where the user left, so the user never has to think _"#%@& where did my data go? is it gone? how to get it back?"_. Never "loose" data without explicit action action of the user.

**Comment by pacproduct** [comment]
Yep, the file is small indeed (56.1KB vs 12.5MB uncompressed) as I forced another compression method than the default one for a smaller file.  
Have you tried uncompressing it with 7-zip? It works well with the default archive manager too on Ubuntu for me.  

Let me now, if it does not work I'll re-upload a standard zip file.

**Comment by josdejong** [comment]
The archive manager of ubuntu correctly opens the file, but fails to extract. I tried `p7zip` on the command line but no luck either.

**Comment by pacproduct** [comment]
Let's hope this version works correctly: [jsoneditor-tests-standard-zip.zip](https://github.com/josdejong/jsoneditor/files/946453/jsoneditor-tests-standard-zip.zip) (2.9MB)

**Comment by josdejong** [comment]
thanks, this one works. I hope to play around with it and do more improvements this weekend.
