### ISSUE TITLE
Element order not preserved

### ISSUE THREAD

**Issue by eduardocoelho** [josdejong/jsoneditor#917]
I use your tool to paste (on the left side) JSON content and then format/review it (on the right side), then I move the formatted version to the left side again and copy the final version to the clipboard.

I usually keep your website opened and paste similar JSON content (same structure/elements, different content). In the previous version, that process would preserve the JSON structure (root elements order). Now the formatted version is apparently random.

**Comment by josdejong** [comment]
Thanks for reporting Eduardo. It doesn't ring a bell immediately. How can I reproduce your issue exactly?

**Comment by eduardocoelho** [comment]
Hi @josdejong .

1. Go to https://jsoneditoronline.org/#, ensure both left/right panels are empty (new document).
2. Paste to the left panel:
```
{
  "id": "the_id",
  "number": 362,
  "title": "title",
  "difficulty": "Medium",
  "size": "15x15",
  "shape": "square",
  "author": "Author Name",
  "multi_word_answer_hint_pattern": "the_pattern",
  "puzzles": [
    {
      "number": 1,
      "contents": "contents...\n",
      "title": "Puzzle 1",
      "id": "id_0001"
    },
    {
      "number": 2,
      "contents": "contents...\n",
      "title": "Puzzle 2",
      "id": "id_0002"
    },
    {
      "number": 3,
      "contents": "contents...\n",
      "title": "Puzzle 3",
      "id": "id_0003"
    },
    {
      "number": 4,
      "contents": "contents...\n",
      "title": "Puzzle 4",
      "id": "id_0004"
    }
  ]
}
```
3. Click `Copy >`.
4. Drag and drop to change the order of the root elements on the right panel, e.g.:
```
{
  "title": "title",
  "author": "Author Name",
  "number": 362,
  "difficulty": "Medium",
  "size": "15x15",
  "shape": "square",
  "id": "the_id",
  "multi_word_answer_hint_pattern": "the_pattern",
  "puzzles": [
    {
      "number": 1,
      "contents": "contents...\n",
      "title": "Puzzle 1",
      "id": "id_0001"
    },
    {
      "number": 2,
      "contents": "contents...\n",
      "title": "Puzzle 2",
      "id": "id_0002"
    },
    {
      "number": 3,
      "contents": "contents...\n",
      "title": "Puzzle 3",
      "id": "id_0003"
    },
    {
      "number": 4,
      "contents": "contents...\n",
      "title": "Puzzle 4",
      "id": "id_0004"
    }
  ]
}
```
5. Click `< Copy`. The left panel will show the version with elements changed, identical to the right panel.
6. Now, suppose you left the website opened, and paste another JSON, with similar structure, to the left panel.:
```
{
  "id": "another_id",
  "number": 363,
  "title": "another title",
  "difficulty": "Hard",
  "size": "15x15",
  "shape": "square",
  "author": "Other Author Name",
  "multi_word_answer_hint_pattern": "another_pattern",
  "puzzles": [
    {
      "number": 1,
      "contents": "contents...\n",
      "title": "Puzzle #1",
      "id": "id_0001"
    },
    {
      "number": 2,
      "contents": "contents...\n",
      "title": "Puzzle #2",
      "id": "id_0002"
    },
    {
      "number": 3,
      "contents": "contents...\n",
      "title": "Puzzle #3",
      "id": "id_0003"
    },
    {
      "number": 4,
      "contents": "contents...\n",
      "title": "Puzzle #4",
      "id": "id_0004"
    }
  ]
}
```
7. Click `Copy >`. You'll see the contents of the left panel updated on the right panel, and the previous element order of the right panel is preserved.
```
{
  "title": "another title",
  "author": "Other Author Name",
  "number": 363,
  "difficulty": "Hard",
  "size": "15x15",
  "shape": "square",
  "id": "another_id",
  "multi_word_answer_hint_pattern": "another_pattern",
  "puzzles": [
    {
      "number": 1,
      "contents": "contents...\n",
      "title": "Puzzle #1",
      "id": "id_0001"
    },
    {
      "number": 2,
      "contents": "contents...\n",
      "title": "Puzzle #2",
      "id": "id_0002"
    },
    {
      "number": 3,
      "contents": "contents...\n",
      "title": "Puzzle #3",
      "id": "id_0003"
    },
    {
      "number": 4,
      "contents": "contents...\n",
      "title": "Puzzle #4",
      "id": "id_0004"
    }
  ]
}
```
8. Now click `< Copy`.

**Expected:** The contents and the element order of the right panel are moved to the left panel, and the left panel looks like:
```
{
  "title": "another title",
  "author": "Other Author Name",
  "number": 363,
  "difficulty": "Hard",
  "size": "15x15",
  "shape": "square",
  "id": "another_id",
  "multi_word_answer_hint_pattern": "another_pattern",
  "puzzles": [
    {
      "number": 1,
      "contents": "contents...\n",
      "title": "Puzzle #1",
      "id": "id_0001"
    },
    {
      "number": 2,
      "contents": "contents...\n",
      "title": "Puzzle #2",
      "id": "id_0002"
    },
    {
      "number": 3,
      "contents": "contents...\n",
      "title": "Puzzle #3",
      "id": "id_0003"
    },
    {
      "number": 4,
      "contents": "contents...\n",
      "title": "Puzzle #4",
      "id": "id_0004"
    }
  ]
}
```

**Actual:** The left panel apparently remains unchanged, the contents are identical to the right panel, but with different element order (identical to the one inserted in step 6.)
```
{
  "id": "another_id",
  "number": 363,
  "title": "another title",
  "difficulty": "Hard",
  "size": "15x15",
  "shape": "square",
  "author": "Other Author Name",
  "multi_word_answer_hint_pattern": "another_pattern",
  "puzzles": [
    {
      "number": 1,
      "contents": "contents...\n",
      "title": "Puzzle #1",
      "id": "id_0001"
    },
    {
      "number": 2,
      "contents": "contents...\n",
      "title": "Puzzle #2",
      "id": "id_0002"
    },
    {
      "number": 3,
      "contents": "contents...\n",
      "title": "Puzzle #3",
      "id": "id_0003"
    },
    {
      "number": 4,
      "contents": "contents...\n",
      "title": "Puzzle #4",
      "id": "id_0004"
    }
  ]
}
```

NOTE: It's not a big issue, but apparently a change of behavior. As a workaround, one could get the final version (expected) code by clicking the `code` switch on the right panel.

**Comment by josdejong** [comment]
Thanks for working out this example on how to reproduce the issue. It's indeed not a big showstopper but really annoying if you can't rely on this order. 

I have done a bit of debugging and have an idea where this might come from, but still have to work out a proper solution for it. Will keep you posted.

**Comment by josdejong** [comment]
This is fixed now in `jsoneditor@8.6.2` and web application `v5.3.3`. Can you give it a try Eduard?

**Comment by eduardocoelho** [comment]
Hi @josdejong . Is there any specific URL to test the new version?
I tried on the default URL (https://jsoneditoronline.org) and Step 7. `Click Copy >. You'll see the contents of the left panel updated on the right panel, and the previous element order of the right panel is preserved.` failed.

**Comment by josdejong** [comment]
You can check whether you're running the latest version of the web application via the "About" modal (button top right), it should be showing `Version: 5.3.4`.

Step 7 is indeed changed: when copying (both from left to right or vice versa), the order of the elements will be updated. Is this not what you expect?

**Comment by eduardocoelho** [comment]
Hi @josdejong . Tested here in version 5.3.4. The issue still occurs (fails at step 7, when you click `Copy >`, the json data on the right panel is updated and the element order from the right panel is lost). The result looks like *Actual* (last paragraph of the reported issue), not *Expected*.

Anyway, this is not a dealbreaker.

**Comment by josdejong** [comment]
I think the confusion is in that the editor now keeps the order of object properties correct in two directions: both when copying from left to right _and_ when copying from right to left.

If I understand you correctly, you would like to keep the order correct when copying from right to left but _not_ when copying from left to right? If so, is there a reason for that?

**Comment by eduardocoelho** [comment]
Hi @josdejong .
The behavior I mentioned occurred in previous versions, and was good for my workflow because I was able to "replace the data" but "keeping the element order". In other words, I was able to keep the element order in the "destination" tab. 

Preserving the element order from the "source" tab (which would contain the new data) and transferring to the "destination" tab would not work, regardless of the direction.

I hope it makes clear what is the issue. Again, this is not a dealbreaker, just a behavior that was lost in the recent updates.

**Comment by josdejong** [comment]
Thanks for your clarification, that's helpful. 

I'm still a bit in doubt about the new behavior. Keeping the order consistent from what you call "destiny" towards "source" makes a lot of sense. But the other way around, from "source" to "destiny" is less obvious since the order of properties in a JSON object is not really guaranteed. I will give it a bit more thought but will probably revert this behavior from "source" to "destiny", ending up with exactly with your desired behavior.

**Comment by josdejong** [comment]
Eduardo I've reverted changing order of properties when updating a JSON document, since this can give tricky side effects because the order of object properties isn't really guaranteed. 

So the latest version (library `v8.6.4`, web application `v5.4.0`) are working exactly according to your expectations :)

**Comment by eduardocoelho** [comment]
Thanks for your time @josdejong !
